name: App Hub publish

env:
    D2_APP_HUB_API_KEY: ${{secrets.D2_APP_HUB_API_KEY}}

# Controls when the action will run.
on:
    # Triggers the workflow when a new release is created
    release:
        types: [created]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - uses: c-hive/gha-yarn-cache@v1

            - name: Install JS dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Release to DHIS2 App Hub
              run: yarn run d2-app-scripts publish

